### ISSUE TITLE
Cannot save product, error "Class "Joomla\CMS\Event\Finder\AfterSaveEvent" not found"

### ISSUE THREAD

**Issue by webgras** [Dudebaker/Virtuemart-Finder#1]
I am on VirtueMart 4.2.16 11030
And Joomla 4.4.6
I tried to change the weight of a product and when I save, I get the following error:
![grafik](https://github.com/user-attachments/assets/2d611914-8e0d-46db-8008-89be754f5c9a)

I published all 5 plugins.
![grafik](https://github.com/user-attachments/assets/98ee597c-e814-4180-a64d-2fd78b27e3cf)

Any ideas?

**Comment by Dudebaker** [comment]
Please try the Version 1.0.1 of the package.
v1.1.0 needs Joomla 5.1 and later.
Will add some notes to the Readme tomorrow.
